export const TRUTH_HIGH_THRESHOLD = 90;
export const TRUTH_LOW_THRESHOLD = 10;

export const DEFAULT_TRUTH_HIGH_THRESHOLD = TRUTH_HIGH_THRESHOLD;
export const DEFAULT_TRUTH_LOW_THRESHOLD = TRUTH_LOW_THRESHOLD;
