import { requiresStateTarget } from '@/game/stateTargeting';
import React, { useRef } from 'react';
import * as DialogPrimitive from '@radix-ui/react-dialog';
import { Button } from '@/components/ui/button';
import { Dialog, DialogPortal, DialogOverlay, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { X, Target, Zap, Megaphone, Trash2, BookOpen } from 'lucide-react';
import type { GameCard } from '@/rules/mvp';
import CardImage from '@/components/game/CardImage';
import { ExtensionCardBadge } from '@/components/game/ExtensionCardBadge';
import { useIsMobile } from '@/hooks/use-mobile';
import { useUiTheme } from '@/hooks/useTheme';
import { formatEffect, getAutoGeneratedCardText, getFactionLabel, getFlavorText, getRarityLabel, normalizeCardType } from '@/lib/cardUi';
import '@/styles/card-inspector.css';

interface CardDetailOverlayProps {
  card: GameCard | null;
  canAfford: boolean;
  disabled: boolean;
  onClose: () => void;
  onPlayCard: () => void;
  swipeHandlers?: Pick<React.HTMLAttributes<HTMLDivElement>, 'onTouchStart' | 'onTouchEnd' | 'onTouchCancel'>;
  isDiscardQueued?: boolean;
  onToggleDiscard?: () => void;
  discardEnabled?: boolean;
  onRequestArticle?: () => void;
  articleAvailable?: boolean;
}

const CardDetailOverlay: React.FC<CardDetailOverlayProps> = ({
  card,
  canAfford,
  disabled,
  onClose,
  onPlayCard,
  swipeHandlers,
  isDiscardQueued = false,
  onToggleDiscard,
  discardEnabled = true,
  onRequestArticle,
  articleAvailable = false,
}) => {
  const [uiTheme] = useUiTheme();
  const isMobile = useIsMobile();
  const returnFocusRef = useRef<HTMLElement | null>(null);
  if (!card) return null;

  const type = normalizeCardType(card.type);
  const ActionIcon = type === 'ZONE' ? Target : type === 'ATTACK' ? Zap : Megaphone;
  const effect = formatEffect(card);
  const flavor = getFlavorText(card);
  const extraText = card.text?.trim();
  const showExtraText = Boolean(extraText && extraText !== effect.trim() && extraText !== getAutoGeneratedCardText(card)?.trim());

  return (
    <Dialog open onOpenChange={(open) => { if (!open) onClose(); }}>
      <DialogPortal>
        <DialogOverlay className="card-inspector-backdrop" />
        <DialogPrimitive.Content
          className="card-inspector"
          data-ui-theme={uiTheme}
          data-faction={card.faction}
          data-card-id={card.id}
          onOpenAutoFocus={() => {
            returnFocusRef.current = document.activeElement instanceof HTMLElement ? document.activeElement : null;
          }}
          onCloseAutoFocus={(event) => {
            event.preventDefault();
            if (returnFocusRef.current?.isConnected) returnFocusRef.current.focus({ preventScroll: true });
          }}
        >
          <header className="card-inspector-header">
            <div className="min-w-0 flex-1">
              <p className="card-inspector-kicker">{getFactionLabel(card.faction)} · {type}</p>
              <DialogTitle className="card-inspector-title">{card.name}</DialogTitle>
              <DialogDescription className="card-inspector-description">
                {getRarityLabel(card.rarity)} asset · {card.cost} IP to deploy
              </DialogDescription>
            </div>
            <Button type="button" variant="ghost" size="icon" onClick={onClose} className="card-inspector-close" aria-label="Close card details">
              <X aria-hidden="true" className="h-5 w-5" />
            </Button>
          </header>

          <div className="card-inspector-scroll" tabIndex={0} role="region" aria-label="Card effect and intelligence">
            <div className="card-inspector-art" {...(isMobile ? swipeHandlers : {})}>
              <CardImage cardId={card.id} className="h-full w-full" fit="contain" />
              <ExtensionCardBadge cardId={card.id} card={card} variant="overlay" />
            </div>
            <div className="card-inspector-copy">
              <section>
                <h3>Effect</h3>
                <p className="card-inspector-effect">{effect}</p>
                {showExtraText && <p>{extraText}</p>}
              </section>
              {flavor && (
                <section className="card-inspector-intelligence">
                  <h3>Classified intelligence</h3>
                  <p>{flavor}</p>
                </section>
              )}
              {requiresStateTarget(card) && <p className="card-inspector-hint">Choose an unowned or rival state after selecting this card.</p>}
            </div>
          </div>

          <footer className="card-inspector-footer">
            <p role="status" className="card-inspector-status">
              {disabled ? 'Deployment unavailable this turn.' : canAfford ? `Ready to deploy · ${card.cost} IP` : `Requires ${card.cost} IP to deploy.`}
              {isDiscardQueued && <span> Queued for discard at turn end.</span>}
            </p>
            <div className="card-inspector-actions">
              <Button type="button" onClick={onPlayCard} disabled={disabled || !canAfford} className="card-inspector-deploy">
                <ActionIcon aria-hidden="true" className="h-4 w-4" />
                {requiresStateTarget(card) ? 'Select & target' : 'Deploy asset'}
              </Button>
              {onToggleDiscard && (
                <Button type="button" variant="outline" onClick={onToggleDiscard} disabled={!discardEnabled} aria-pressed={isDiscardQueued} className="card-inspector-discard">
                  <Trash2 aria-hidden="true" className="h-4 w-4" />
                  {isDiscardQueued ? 'Undo discard' : 'Discard at turn end'}
                </Button>
              )}
              <Button
                type="button"
                variant="outline"
                onClick={() => {
                  // The article dialog owns focus once it replaces the inspector.
                  returnFocusRef.current = null;
                  onRequestArticle?.();
                }}
                disabled={!articleAvailable || !onRequestArticle}
                title={!articleAvailable ? 'No linked article for this asset' : undefined}
              >
                <BookOpen aria-hidden="true" className="h-4 w-4" />
                Read article
              </Button>
            </div>
          </footer>
        </DialogPrimitive.Content>
      </DialogPortal>
    </Dialog>
  );
};

export default CardDetailOverlay;
