// AUTO-GENERATED by rewrite-cards-unified.ts

import type { Card } from "../../types/mvpCard";

export const CARD_DATABASE_CORE_REWRITTEN: Card[] = [
  {
    id: "GOV-051",
    name: "Men in Black Squad",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Nobody remembers the encounter… and that's the point.",
  },
  {
    id: "GOV-052",
    name: "Weather Control Division",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Forecast: 100% chance of plausible deniability.",
  },
  {
    id: "GOV-053",
    name: "Cigarette Whisperer",
    faction: "government",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "His smoke breaks last decades.",
  },
  {
    id: "GOV-054",
    name: "Operation Mockingbird 2.0",
    faction: "government",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Sponsored by your friendly neighborhood broadcast network.",
  },
  {
    id: "GOV-055",
    name: "National Security Red Tape",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Forms must be filed in triplicate, notarized, and burned.",
  },
  {
    id: "GOV-056",
    name: "Shadow Budget",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Somewhere, in an Excel sheet nobody is allowed to open.",
  },
  {
    id: "GOV-057",
    name: "Alien Autopsy Cover-Up",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Grainy VHS footage? Totally fake. Trust us.",
  },
  {
    id: "GOV-058",
    name: "Black Site Expansion",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "You'll never find it on Google Maps.",
  },
  {
    id: "GOV-059",
    name: "Patriot Act Reloaded",
    faction: "government",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "For your safety. Definitely not ours.",
  },
  {
    id: "GOV-060",
    name: "Mind Control Fluoride",
    faction: "government",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "It's in the water. Drink up.",
  },
  {
    id: "GOV-061",
    name: "Department of Denials",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "\"We can neither confirm nor deny…\"",
  },
  {
    id: "GOV-062",
    name: "Krycek the Double Agent",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "He works for everyone. And no one.",
  },
  {
    id: "GOV-063",
    name: "Eternal Committee Hearing",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Please hold. Your conspiracy is important to us.",
  },
  {
    id: "GOV-064",
    name: "Big Brother Surveillance",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Your camera is on.",
  },
  {
    id: "GOV-065",
    name: "Agent Smitherson Cameo",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Always in the background, always adjusting his tie.",
  },
  {
    id: "GOV-066",
    name: "Underground Archive",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Microfilm never dies.",
  },
  {
    id: "GOV-067",
    name: "Spin Control Office",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "The narrative never rests.",
  },
  {
    id: "GOV-068",
    name: "Crash Retrieval Zone",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Shiny wreckage becomes classified instantly.",
  },
  {
    id: "GOV-069",
    name: "Closed Session",
    faction: "government",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "All cameras off, all lies on.",
  },
  {
    id: "GOV-070",
    name: "Psych Ops Lab",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Testing slogans on rats and voters alike.",
  },
  {
    id: "GOV-071",
    name: "Red Phone Network",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "One ring controls all.",
  },
  {
    id: "GOV-072",
    name: "Containment Zone",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Cones, tape, and classified tape.",
  },
  {
    id: "GOV-073",
    name: "Obfuscation Bureau",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "The truth hurts, but pays well.",
  },
  {
    id: "GOV-074",
    name: "FOIA Shredder Room",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "The shredder is always hungry.",
  },
  {
    id: "GOV-075",
    name: "National Guard Rollout",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Nothing to see, nothing to seize.",
  },
  {
    id: "GOV-076",
    name: "Redaction Vault",
    faction: "government",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "█████████ everywhere.",
  },
  {
    id: "GOV-077",
    name: "Satellite Uplink",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Every ping is patriotism.",
  },
  {
    id: "GOV-078",
    name: "Political Lobby",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Bribes are the sincerest form of flattery.",
  },
  {
    id: "GOV-079",
    name: "Crisis Management Zone",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Every crisis needs a committee.",
  },
  {
    id: "GOV-080",
    name: "Continuity Bunker",
    faction: "government",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "Built for a rainy doomsday.",
  },
  {
    id: "GOV-081",
    name: "Spin Doctors' Lounge",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Prescription: more headlines.",
  },
  {
    id: "GOV-082",
    name: "Federal PsyOps Center",
    faction: "government",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "Their nightmares are our research notes.",
  },
  {
    id: "GOV-083",
    name: "Temporal Containment Lab",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "We filed time under Pending.",
  },
  {
    id: "GOV-084",
    name: "Council of the Unseen",
    faction: "government",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Minutes vanish, so do freedoms.",
  },
  {
    id: "GOV-085",
    name: "Front Organization",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Looks legit, smells classified.",
  },
  {
    id: "GOV-086",
    name: "Controlled Media Outlet",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Your news, their loss.",
  },
  {
    id: "GOV-087",
    name: "Continuity of Message",
    faction: "government",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "We repeat until it becomes history.",
  },
  {
    id: "GOV-088",
    name: "Surplus MRAP Parade",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Intimidation is a safety feature.",
  },
  {
    id: "GOV-089",
    name: "Continuity Servers",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Backups for backups.",
  },
  {
    id: "GOV-090",
    name: "Airport Media Pen",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Roped-off narratives.",
  },
  {
    id: "GOV-091",
    name: "Compliance Audit",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Forms first, outrage later.",
  },
  {
    id: "GOV-092",
    name: "Continuity Signal Test",
    faction: "government",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "This is only a drill. Or is it?",
  },
  {
    id: "GOV-093",
    name: "Perimeter Cameras",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "The red light means 'welcome'.",
  },
  {
    id: "GOV-094",
    name: "Leaker's New Job",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Promotion to 'Elsewhere'.",
  },
  {
    id: "GOV-095",
    name: "Data Fusion Hub",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Interoperability is when everyone watches you together.",
  },
  {
    id: "GOV-096",
    name: "Dry-Labbed Results",
    faction: "government",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Peer review by peers we hired.",
  },
  {
    id: "GOV-097",
    name: "Wilderness Listening Post",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Owls aren't what they seem. Neither are antennas.",
  },
  {
    id: "GOV-098",
    name: "National Security Letter",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Gag orders pair well with coffee.",
  },
  {
    id: "GOV-099",
    name: "Asset Laundering",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "We dry-clean money and reputations.",
  },
  {
    id: "GOV-100",
    name: "Harbor Dock Warehouse",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Manifest says 'miscellaneous'.",
  },
  {
    id: "TRUTH-076",
    name: "Florida Roadside Attraction",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Gator wrestling, Elvis impersonator optional.",
  },
  {
    id: "TRUTH-077",
    name: "Ghost Town Saloon",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Bartender vanished in 1893, still pouring.",
  },
  {
    id: "TRUTH-078",
    name: "Roswell Tourist Center",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "We sell postcards and plausible deniability.",
  },
  {
    id: "TRUTH-079",
    name: "Mothman Statue Plaza",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Tourist trap with prophetic wings.",
  },
  {
    id: "TRUTH-080",
    name: "Haunted Lighthouse",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Fog horn occasionally says your name.",
  },
  {
    id: "TRUTH-081",
    name: "Conspiracy Archive Locker",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Files stacked by string color.",
  },
  {
    id: "TRUTH-082",
    name: "Bigfoot Footprint Trail",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Size 28 evidence, mind the puddles.",
  },
  {
    id: "TRUTH-083",
    name: "Elvis Chapel Roadside",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Love me tender, pay me weekly.",
  },
  {
    id: "TRUTH-084",
    name: "Skywatch Ridge",
    faction: "truth",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "Blankets, binoculars, and bleeping.",
  },
  {
    id: "TRUTH-085",
    name: "County Fair Crop Lab",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Blue ribbon for best geometry.",
  },
  {
    id: "TRUTH-086",
    name: "FOIA Lawsuit",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Your honor, we respectfully unredact.",
  },
  {
    id: "TRUTH-087",
    name: "X-Files Marathon",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Season 3 unlocks your third eye.",
  },
  {
    id: "TRUTH-088",
    name: "Elvis Flashmob",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Sequins are blinding…and binding.",
  },
  {
    id: "TRUTH-089",
    name: "Citizen Drone Recon",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Beep boop, nice try, spooks.",
  },
  {
    id: "TRUTH-090",
    name: "Night-Vision Stakeout",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Green tint, clear intent.",
  },
  {
    id: "TRUTH-091",
    name: "Bigfoot Press Conference",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Microphones mysteriously smeared with mud.",
  },
  {
    id: "TRUTH-092",
    name: "Mothman Siren Test",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "The warning no one can ignore.",
  },
  {
    id: "TRUTH-093",
    name: "Call-in Show Frenzy",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Lines lit, lies dimmed.",
  },
  {
    id: "TRUTH-094",
    name: "Fact-Check Brigade",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Receipts loaded; caps locked.",
  },
  {
    id: "TRUTH-095",
    name: "Neighborhood Cameras",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Smile, you're de-escalated.",
  },
  {
    id: "TRUTH-096",
    name: "Emergency Press Conference",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Live rebuttal beats late retraction.",
  },
  {
    id: "TRUTH-097",
    name: "Glitch in the Matrix",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Oops, the simulation dropped a frame.",
  },
  {
    id: "TRUTH-098",
    name: "Open-Source UFO Tracker",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Git push: disclosure.",
  },
  {
    id: "TRUTH-099",
    name: "Grassroots Crowdfunding",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "One micro-donation at a time.",
  },
  {
    id: "TRUTH-100",
    name: "Mothership Over D.C.",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Take me to your committee chair.",
  },
  {
    id: "TRUTH-151",
    name: "Elvis Volunteers at Animal Shelter",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Hound dogs approved.",
  },
  {
    id: "TRUTH-152",
    name: "Bat Boy Hosts the Evening News",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Top story: screamingly credible.",
  },
  {
    id: "TRUTH-153",
    name: "Florida Man's Meteor Fragment",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Hot rock, hotter takes.",
  },
  {
    id: "TRUTH-154",
    name: "Pastor Rex Declares Open Files Week",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Bring your own highlighter.",
  },
  {
    id: "TRUTH-155",
    name: "Agent Smitherson Leaves a Voicemail",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "'Do not call back.' *Beep.*",
  },
  {
    id: "TRUTH-156",
    name: "Crowd Spots Triangle Craft",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Geometry class finally pays off.",
  },
  {
    id: "TRUTH-157",
    name: "Elvis Charity Telethon",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "All donations tax-deductible from reality.",
  },
  {
    id: "TRUTH-158",
    name: "UFO Traffic Cam Compilation",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Please merge truthfully.",
  },
  {
    id: "TRUTH-159",
    name: "Bat Boy Op-Ed: 'I Was There'",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Has the receipts, keeps the screams.",
  },
  {
    id: "TRUTH-160",
    name: "Grandma's Séance Transcript",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Meeting minutes by planchette.",
  },
  {
    id: "TRUTH-161",
    name: "Elvis Delivers FOIA Request",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Return address: The Heartbreak Hotel.",
  },
  {
    id: "TRUTH-162",
    name: "MIB Parking Ticket Goes Viral",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Violation: obvious saucer.",
  },
  {
    id: "TRUTH-163",
    name: "Florida Man's Paranormal BBQ",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Ribs and revelations.",
  },
  {
    id: "TRUTH-164",
    name: "Bat Boy Wins Journalism Award",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Accepted with a polite shriek.",
  },
  {
    id: "TRUTH-165",
    name: "Elvis Bus Tour to Area 51",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "No cameras, only camcorders.",
  },
  {
    id: "TRUTH-166",
    name: "Community Leak Drop",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "The cloud is just a sky hard drive.",
  },
  {
    id: "TRUTH-167",
    name: "Paranormal Bake Sale",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Cupcakes with classified sprinkles.",
  },
  {
    id: "TRUTH-168",
    name: "Elvis Hologram Town Hall",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Questions answered, hips simulated.",
  },
  {
    id: "TRUTH-169",
    name: "Blurry Angel Over Courthouse",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Attached wings, unattached verdict.",
  },
  {
    id: "TRUTH-170",
    name: "Agent Smitherson Misplaces Briefcase",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Contents: oops, everything.",
  },
  {
    id: "TRUTH-171",
    name: "Crowdfunded Telescope Network",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Eyes everywhere, budget nowhere.",
  },
  {
    id: "TRUTH-172",
    name: "Tabloid 'Truth or Dare' Special",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Dares accepted by democracy.",
  },
  {
    id: "TRUTH-173",
    name: "Elvis Roadhouse",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Open late, secrets later.",
  },
  {
    id: "TRUTH-174",
    name: "Bat Boy Youth Center",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Homework: screaming practice.",
  },
  {
    id: "TRUTH-175",
    name: "Haunted Subway Platform",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Next arrival: transparency.",
  },
  {
    id: "TRUTH-176",
    name: "Community Print Shop",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Ink smudges improve credibility.",
  },
  {
    id: "TRUTH-177",
    name: "Lake Monster Boardwalk",
    faction: "truth",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "Souvenir shops sell periscopes.",
  },
  {
    id: "TRUTH-178",
    name: "Paranormal Podcast Studio",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Recorded live in an undisclosed basement.",
  },
  {
    id: "TRUTH-179",
    name: "Conspiracy Flea Market",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Gently used evidence.",
  },
  {
    id: "TRUTH-180",
    name: "Ghost-Lit Lighthouse",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Beam bends around secrets.",
  },
  {
    id: "TRUTH-181",
    name: "Elvis Chapel of Revelations",
    faction: "truth",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "Choir hums suspiciously familiar melodies.",
  },
  {
    id: "TRUTH-182",
    name: "Bat Boy Archives",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Files arranged by shriek pitch.",
  },
  {
    id: "TRUTH-183",
    name: "Open Mic Press Briefing",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Mic check, lie wreck.",
  },
  {
    id: "TRUTH-184",
    name: "Neighborhood Drone Surge",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Eyes in the sky, pies on the porch.",
  },
  {
    id: "TRUTH-185",
    name: "Leaks to Local Paper",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Ink beats intimidation.",
  },
  {
    id: "TRUTH-186",
    name: "Citizen Audit",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Receipts stapled to reality.",
  },
  {
    id: "TRUTH-187",
    name: "Midnight Signal Boost",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Static speaks volumes.",
  },
  {
    id: "TRUTH-188",
    name: "Counter-Spin Workshop",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Spin class for facts.",
  },
  {
    id: "TRUTH-189",
    name: "FOIA Blitz Marathon",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Paper cuts to the narrative.",
  },
  {
    id: "TRUTH-190",
    name: "Flash Mob Fact-Check",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Synchronised citations.",
  },
  {
    id: "TRUTH-191",
    name: "Mothman Siren",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Wings over weak points.",
  },
  {
    id: "TRUTH-192",
    name: "Copier Jam of Destiny",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Paper wins this round.",
  },
  {
    id: "TRUTH-193",
    name: "Neighborhood Witness Net",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "We saw that coming.",
  },
  {
    id: "TRUTH-194",
    name: "Courthouse Candlelight Vigil",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Light pierces ledger lines.",
  },
  {
    id: "TRUTH-195",
    name: "Ghost Jury Nullification",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Overruled by the afterlife.",
  },
  {
    id: "TRUTH-196",
    name: "Open Source Investigators",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Threads that pull threads.",
  },
  {
    id: "TRUTH-197",
    name: "Tabloid Freedom Fund",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Small bills fund big stories.",
  },
  {
    id: "TRUTH-198",
    name: "Community Wi-Fi of Truth",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Password: OpenEverything.",
  },
  {
    id: "TRUTH-199",
    name: "Elvis Time Capsule",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Contents: one sequined future.",
  },
  {
    id: "TRUTH-200",
    name: "The Final Disclosure",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "The last page of the last secret file.",
  },
  {
    id: "GOV-101",
    name: "Man with the Match",
    faction: "government",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "He lights the story before it's written.",
  },
  {
    id: "GOV-102",
    name: "Left-Handed Partner",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "He shakes with one hand and pockets with the other.",
  },
  {
    id: "GOV-103",
    name: "Subcommittee X",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "The agenda item is secrecy.",
  },
  {
    id: "GOV-104",
    name: "Deep Motor Pool",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Unmarked, unlimited, unavailable.",
  },
  {
    id: "GOV-105",
    name: "Cutouts and Cover Names",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Everyone knows no one.",
  },
  {
    id: "GOV-106",
    name: "Routine Satellite Test",
    faction: "government",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Routine. Repeated. Reassuring.",
  },
  {
    id: "GOV-107",
    name: "Document Sanitization Bay",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Bleach for inconvenient ink.",
  },
  {
    id: "GOV-108",
    name: "Joint Task Force: Optics",
    faction: "government",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Perception is nine-tenths of reality.",
  },
  {
    id: "GOV-109",
    name: "Asset Relocation",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Subjects moved. Storyline removed.",
  },
  {
    id: "GOV-110",
    name: "Desert Listening Array",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "The wind carries more than sand.",
  },
  {
    id: "GOV-111",
    name: "Compliance Architecture",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "The system defends itself.",
  },
  {
    id: "GOV-112",
    name: "Federalization Order",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Local control, centrally approved.",
  },
  {
    id: "GOV-113",
    name: "Subterranean Tram",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Fast track to nowhere you know.",
  },
  {
    id: "GOV-114",
    name: "Credible Source Program",
    faction: "government",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Blue checks for black ops.",
  },
  {
    id: "GOV-115",
    name: "Intelligence Reprogramming",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "A budget is a moral narrative.",
  },
  {
    id: "GOV-116",
    name: "Runway Hangar C",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Closed for renovations since forever.",
  },
  {
    id: "GOV-117",
    name: "Red Team Leak Drill",
    faction: "government",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Practice makes perfect headlines.",
  },
  {
    id: "GOV-118",
    name: "Black Ledger",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Numbers that never audit.",
  },
  {
    id: "GOV-119",
    name: "Harbor Quarantine Pier",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Hold the cargo. Hold the narrative.",
  },
  {
    id: "GOV-120",
    name: "Clearance Revoked",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Trust withdrawn at the speed of pen.",
  },
  {
    id: "GOV-121",
    name: "Asset Forfeiture Sweep",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Everything not nailed down becomes evidence.",
  },
  {
    id: "GOV-122",
    name: "Records Suspension Wing",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "The filing cabinets hum ominously.",
  },
  {
    id: "GOV-123",
    name: "Press Credentials Review",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Access is a privilege with paperwork.",
  },
  {
    id: "GOV-124",
    name: "Narrative Harmonization",
    faction: "government",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Bring all voices into one key.",
  },
  {
    id: "GOV-125",
    name: "Remote Hearing Room",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Muted. Camera off. Case closed.",
  },
  {
    id: "GOV-126",
    name: "Compelled Testimony",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Answer the question you weren't asked.",
  },
  {
    id: "GOV-127",
    name: "Continuity of Narrative",
    faction: "government",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Repetition is retention.",
  },
  {
    id: "GOV-128",
    name: "Aquifer Sensor Farm",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "The waters whisper; we record.",
  },
  {
    id: "GOV-129",
    name: "Strategic Denial",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "We categorically decline reality.",
  },
  {
    id: "GOV-130",
    name: "Routine Systems Upgrade",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Security patches for public perception.",
  },
  {
    id: "GOV-131",
    name: "Observation Deck 51",
    faction: "government",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "The best view is from behind glass.",
  },
  {
    id: "GOV-132",
    name: "Guilt by Spreadsheet",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Cell B2 says you're compromised.",
  },
  {
    id: "GOV-133",
    name: "Narrative Freeze Frame",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Stop motion truth.",
  },
  {
    id: "GOV-134",
    name: "Sealed Loading Dock",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "All shipments marked 'later'.",
  },
  {
    id: "GOV-135",
    name: "Global Reassurance Tour",
    faction: "government",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Handshake, headline, hush.",
  },
  {
    id: "GOV-136",
    name: "Executive Summary Only",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "We read what matters. You read what remains.",
  },
  {
    id: "GOV-137",
    name: "Cold Storage Vault",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Put the facts on ice.",
  },
  {
    id: "GOV-138",
    name: "Seize the Servers",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "A warrant, a forklift, a silence.",
  },
  {
    id: "GOV-139",
    name: "Calibrated Denials",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Precision-crafted statements of nothing.",
  },
  {
    id: "GOV-140",
    name: "PR Blackout Grid",
    faction: "government",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Darken the lights, dim the doubts.",
  },
  {
    id: "GOV-141",
    name: "Rail Spur to Nowhere",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Every track leads off-map.",
  },
  {
    id: "GOV-142",
    name: "Liaison to the Syndicate",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Partnerships need no sunlight.",
  },
  {
    id: "GOV-143",
    name: "Friendly Fact-Checker Program",
    faction: "government",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Missing context, found budget.",
  },
  {
    id: "GOV-144",
    name: "Jurisdiction Maze",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "By the time you arrive, you're out of bounds.",
  },
  {
    id: "GOV-145",
    name: "Emergency Broadcast Hijack",
    faction: "government",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Your regularly scheduled reality has been rescheduled.",
  },
  {
    id: "GOV-146",
    name: "Black Budget Surge",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Money talks. In code names.",
  },
  {
    id: "GOV-147",
    name: "Syndicate Directive Zero",
    faction: "government",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Decisions made above clearance.",
  },
  {
    id: "GOV-148",
    name: "Overnight Guidelines",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Reality must adhere to policy.",
  },
  {
    id: "GOV-149",
    name: "Confiscated Hard Drives",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "A persistent storage problem.",
  },
  {
    id: "GOV-150",
    name: "Council in the Smoke",
    faction: "government",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "When the room clears, the map has changed.",
  },
  {
    id: "TRUTH-001",
    name: "Blurry Bigfoot Photo Goes Viral",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Experts confirm: pixels don't lie.",
  },
  {
    id: "TRUTH-002",
    name: "Elvis Spotted at 3 A.M. Diner",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "The King recommends the midnight pancakes.",
  },
  {
    id: "TRUTH-003",
    name: "Pastor Rex's Apocalypse Podcast",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Sponsored by Doomsday Beans™.",
  },
  {
    id: "TRUTH-004",
    name: "Bat Boy Endorses Transparency",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "His platform: windows with no curtains.",
  },
  {
    id: "TRUTH-005",
    name: "Alien Wedding Blocks Traffic",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Rice thrown… immediately abducted.",
  },
  {
    id: "TRUTH-006",
    name: "Local Grandma Sees Two Ghosts",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "They politely asked for tea.",
  },
  {
    id: "TRUTH-007",
    name: "UFO Over High School Football Game",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Halftime show beamed in from Andromeda.",
  },
  {
    id: "TRUTH-008",
    name: "Cryptid Selfie Goes Mainstream",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "#NoFilter #DefinitelyReal",
  },
  {
    id: "TRUTH-009",
    name: "Elvis Opens Community Garden",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "He composts the tabloids.",
  },
  {
    id: "TRUTH-010",
    name: "Tabloid Thunder Special Edition",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Ink smudges reveal more than black bars.",
  },
  {
    id: "TRUTH-011",
    name: "Mothership Livestream Crashes App",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Chat: 'first!'",
  },
  {
    id: "TRUTH-012",
    name: "Florida Man Joins the Resistance",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "He brought snacks. Questionable snacks.",
  },
  {
    id: "TRUTH-013",
    name: "Elvis Busks in Area 51 Parking Lot",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Tip jar shaped like a saucer.",
  },
  {
    id: "TRUTH-014",
    name: "Citizen Journalist Scoop",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Phones are better than binoculars.",
  },
  {
    id: "TRUTH-015",
    name: "Crop Circle Art Festival",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "BYO tractor.",
  },
  {
    id: "TRUTH-016",
    name: "Tabloid Whistleblower",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "The squeak heard round the world.",
  },
  {
    id: "TRUTH-017",
    name: "Bat Boy Meets Bigfoot",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Historic handshake, very furry.",
  },
  {
    id: "TRUTH-018",
    name: "Elvis the UFO Pilot",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Thank you, interstellar much.",
  },
  {
    id: "TRUTH-019",
    name: "Haunted Walmart",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Rollback prices on cursed dolls.",
  },
  {
    id: "TRUTH-020",
    name: "Cornfield Abduction Site",
    faction: "truth",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "Free tractor rides included.",
  },
  {
    id: "TRUTH-021",
    name: "Bigfoot Campground",
    faction: "truth",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "Please don't feed the senator.",
  },
  {
    id: "TRUTH-022",
    name: "Elvis Shrine in Vegas",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Burning love, steady income.",
  },
  {
    id: "TRUTH-023",
    name: "Grandma's Haunted Basement",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Knitting needles levitate on Tuesdays.",
  },
  {
    id: "TRUTH-024",
    name: "Tabloid Printing Warehouse",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Ink stains reveal hidden messages.",
  },
  {
    id: "TRUTH-025",
    name: "Ghost Hunter Motel",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Room service knocks itself.",
  },
  {
    id: "TRUTH-126",
    name: "Community Scanner Net",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Airwaves have nothing to hide.",
  },
  {
    id: "TRUTH-127",
    name: "Cryptid Petting Zoo",
    faction: "truth",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "Waiver includes claws and clauses.",
  },
  {
    id: "TRUTH-128",
    name: "College Radio Conspiracy Hour",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Playlists of leaks and licks.",
  },
  {
    id: "TRUTH-129",
    name: "Elvis Tribute Casino Lounge",
    faction: "truth",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "House always wins—unless truth shows up.",
  },
  {
    id: "TRUTH-130",
    name: "Public-Access TV Studio",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Tonight on 'Open Secrets': everything.",
  },
  {
    id: "TRUTH-131",
    name: "Haunted National Park",
    faction: "truth",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "Leave only footprints; hear many more.",
  },
  {
    id: "TRUTH-132",
    name: "Data Breach Whistle",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "The loudest tiny whistle ever printed.",
  },
  {
    id: "TRUTH-133",
    name: "Press Conference Ambush",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "First question, final answer.",
  },
  {
    id: "TRUTH-134",
    name: "FOIA Lightning Round",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Redaction ink runs in the rain.",
  },
  {
    id: "TRUTH-135",
    name: "Infiltrate the Briefing",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Credentials printed on recycled secrets.",
  },
  {
    id: "TRUTH-136",
    name: "Crowdsourced Fact Storm",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "1,000 comments, one conclusion.",
  },
  {
    id: "TRUTH-137",
    name: "Operation Spotlight",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Stage lights melt alibis.",
  },
  {
    id: "TRUTH-138",
    name: "Emergency Broadcast Override",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "We interrupt your regularly scheduled denial.",
  },
  {
    id: "TRUTH-139",
    name: "Street Reporter Blitz",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Microphones swarm like bees.",
  },
  {
    id: "TRUTH-140",
    name: "Subpoena Surprise",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Signed by Judge Public Opinion.",
  },
  {
    id: "TRUTH-141",
    name: "Elvis Press Pass",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Laminate of destiny.",
  },
  {
    id: "TRUTH-142",
    name: "Flash-Truth Rally",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Chants harmonize with sirens.",
  },
  {
    id: "TRUTH-143",
    name: "Phone Tree Counterintel",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Ring once if it's a cover-up.",
  },
  {
    id: "TRUTH-144",
    name: "Ghost Patrol",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Boo! Also, bookkeeping.",
  },
  {
    id: "TRUTH-145",
    name: "Public Records Shield",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Stapled, stamped, safe.",
  },
  {
    id: "TRUTH-146",
    name: "Witness Hotline",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Press 1 to spill, press 2 to bill.",
  },
  {
    id: "TRUTH-147",
    name: "Mothership Cover",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Umbrella policy: extraterrestrial.",
  },
  {
    id: "TRUTH-148",
    name: "Tabloid Legal Eagles",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Objection sustained, publicity gained.",
  },
  {
    id: "TRUTH-149",
    name: "Bigfoot Senate Campaign",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "A platform of planks and footprints.",
  },
  {
    id: "TRUTH-150",
    name: "Elvis: The Immortal King",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Long live the King—and the headline.",
  },
  {
    id: "TRUTH-101",
    name: "The Lone Gunmen",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Three hackers, zero hygiene, one friend on the inside.",
  },
  {
    id: "TRUTH-102",
    name: "Open-Records Taskforce",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "If it's stamped 'secret', it's stapled to our to-do list.",
  },
  {
    id: "TRUTH-103",
    name: "Grassroots Press Co-Op",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Ink by the people, for the people.",
  },
  {
    id: "TRUTH-104",
    name: "Citizen Forensics Lab",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Microscopes donated, miracles improvised.",
  },
  {
    id: "TRUTH-105",
    name: "Truth Meter Calibrator",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Batteries not included. Lies excluded.",
  },
  {
    id: "TRUTH-106",
    name: "Tinfoil Supply Chain",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Industrial-grade hats for industrial-sized cover-ups.",
  },
  {
    id: "TRUTH-107",
    name: "Elvis Works the Night Shift",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Punches in with a glittery glove.",
  },
  {
    id: "TRUTH-108",
    name: "Bat Boy Delivers Breaking News",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Screams in AP style.",
  },
  {
    id: "TRUTH-109",
    name: "Pastor Rex Calls Out the Lizard Cabal",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Tail between their legs, allegedly.",
  },
  {
    id: "TRUTH-110",
    name: "Florida Man Finds Government Device",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "He used it to open soda first.",
  },
  {
    id: "TRUTH-111",
    name: "MIB Slip Up on Live TV",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Blink and you'll still see it.",
  },
  {
    id: "TRUTH-112",
    name: "Elvis Joins a Book Club",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Reads only paperbacks—no fingerprints.",
  },
  {
    id: "TRUTH-113",
    name: "Agent Smitherson's Conscience",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "He anonymously CC'd everyone.",
  },
  {
    id: "TRUTH-114",
    name: "Blurry Mothman Dashcam",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Wingspan: entire windshield.",
  },
  {
    id: "TRUTH-115",
    name: "Ghost Jury Finds the Truth",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Verdict echoes for eternity.",
  },
  {
    id: "TRUTH-116",
    name: "Elvis Edits the Front Page",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Headline: 'Love Me Tender, Tell Me Everything'.",
  },
  {
    id: "TRUTH-117",
    name: "Local Kid Interviews a Gray",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "First question: favorite ice cream?",
  },
  {
    id: "TRUTH-118",
    name: "Bat Boy Launches a Zine",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Stapled with bravado.",
  },
  {
    id: "TRUTH-119",
    name: "Psychic Predicts File Drop",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Knew you'd play this.",
  },
  {
    id: "TRUTH-120",
    name: "Desert Billboards of Truth",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Text too big to redact.",
  },
  {
    id: "TRUTH-121",
    name: "Bat Boy Community Center",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "After-school programs for aspiring screamers.",
  },
  {
    id: "TRUTH-122",
    name: "Elvis Roadside Chapel",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Vows exchanged, lies annulled.",
  },
  {
    id: "TRUTH-123",
    name: "Skywatcher Ridge",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Bring blankets, witness meteors and memos.",
  },
  {
    id: "TRUTH-124",
    name: "Conspiracy Coffee Roasters",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Single-origin skepticism.",
  },
  {
    id: "TRUTH-125",
    name: "Haunted Library Stacks",
    faction: "truth",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "Shhh… the books whisper back.",
  },
  {
    id: "truth-1",
    name: "Leaked Documents",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "The people have a right to know.",
  },
  {
    id: "truth-2",
    name: "Investigative Report",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Facts speak louder than fiction.",
  },
  {
    id: "GOV-151",
    name: "Continuity Briefing: Omega",
    faction: "government",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "The fewer details, the greater the reassurance.",
  },
  {
    id: "GOV-152",
    name: "Counter-Influence Bureau",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Every talking point has a billing code.",
  },
  {
    id: "GOV-153",
    name: "Docu-Dump Friday",
    faction: "government",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Transparency occurs when no one's looking.",
  },
  {
    id: "GOV-154",
    name: "Railhead Logistics Yard",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Inbound: pallets of acronyms.",
  },
  {
    id: "GOV-155",
    name: "Hearing Without Cameras",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Public oversight—privately conducted.",
  },
  {
    id: "GOV-156",
    name: "Unmarked Couriers",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "The signature is a wink.",
  },
  {
    id: "GOV-157",
    name: "Observation Balloon Farm",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Weather data, rumor data—air is air.",
  },
  {
    id: "GOV-158",
    name: "Guidance Memo Leak",
    faction: "government",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "If it leaks on time, it isn't an accident.",
  },
  {
    id: "GOV-159",
    name: "Black Funnel Accounts",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "A river of funds with no banks.",
  },
  {
    id: "GOV-160",
    name: "Checkpoint Echo",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "License, registration, and intentions.",
  },
  {
    id: "GOV-161",
    name: "Blackout Order",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "The story will be told later. Maybe.",
  },
  {
    id: "GOV-162",
    name: "Detention Annex 7",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "A file folder with doors.",
  },
  {
    id: "GOV-163",
    name: "Rapid Response Press Pool",
    faction: "government",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Questions pre-approved, answers pre-written.",
  },
  {
    id: "GOV-164",
    name: "Continuity Shuttle",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "From somewhere to nowhere in one stop.",
  },
  {
    id: "GOV-165",
    name: "Operation Soft Silence",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "A quiet call at a loud hour.",
  },
  {
    id: "GOV-166",
    name: "Glacier Records Unit",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Paperwork moves at the speed of ice.",
  },
  {
    id: "GOV-167",
    name: "Interagency Chokepoint",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Passes available in theory.",
  },
  {
    id: "GOV-168",
    name: "Narrative Curators",
    faction: "government",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "We pick what people remember.",
  },
  {
    id: "GOV-169",
    name: "Tarmac Hush Zone",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Jet fuel evaporates, rumors too.",
  },
  {
    id: "GOV-170",
    name: "Executive Summary Leak",
    faction: "government",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "The abstract tells a comforting story.",
  },
  {
    id: "GOV-171",
    name: "Red Cell Simulations",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Practice makes pressure.",
  },
  {
    id: "GOV-172",
    name: "Above-Top-Secret Vault",
    faction: "government",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "The lock has a clearance.",
  },
  {
    id: "GOV-173",
    name: "Quietly Amended",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "The edit history is patriotic.",
  },
  {
    id: "GOV-174",
    name: "Harbor Quarantine Yard",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "The tide waits on paperwork.",
  },
  {
    id: "GOV-175",
    name: "Directive: Total Information",
    faction: "government",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Every signal is a confession.",
  },
  {
    id: "GOV-176",
    name: "Press Credentials Purge",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Access revoked for service rendered.",
  },
  {
    id: "GOV-177",
    name: "Perimeter Tripwire Grid",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "The map is the minefield.",
  },
  {
    id: "GOV-178",
    name: "Spin Cycle Marathon",
    faction: "government",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "We keep talking so you don't have to think.",
  },
  {
    id: "GOV-179",
    name: "Cutout Relay Chain",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "A daisy chain of deniability.",
  },
  {
    id: "GOV-180",
    name: "Desert Boneyard Annex",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Miles of wings, gallons of dust.",
  },
  {
    id: "GOV-181",
    name: "Executive Waiver Stack",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "A paper wall is still a wall.",
  },
  {
    id: "GOV-182",
    name: "Asset Reassignment",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Budgets travel faster than rumors.",
  },
  {
    id: "GOV-183",
    name: "Signal Spoof Lab",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "The airwaves learn to lie.",
  },
  {
    id: "GOV-184",
    name: "Calm the Waters",
    faction: "government",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "A still surface hides any depth.",
  },
  {
    id: "GOV-185",
    name: "Procurement Overrun",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "We overspent on silence.",
  },
  {
    id: "GOV-186",
    name: "Council Elevator",
    faction: "government",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "It only goes down.",
  },
  {
    id: "GOV-187",
    name: "Mirrored Interrogation",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Answer yourself, on the record.",
  },
  {
    id: "GOV-188",
    name: "Syndicate Nightfall",
    faction: "government",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "When the lights go out, the map stops moving.",
  },
  {
    id: "GOV-189",
    name: "Hangar Theta",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Authorized personnel invent authorization.",
  },
  {
    id: "GOV-190",
    name: "Rapid Rebuttal Room",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "The best offense is a press release.",
  },
  {
    id: "GOV-191",
    name: "Command Uplink Bluff",
    faction: "government",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "The blinking lights mean it's working.",
  },
  {
    id: "GOV-192",
    name: "Intercept Hub",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Every line ends in our pocket.",
  },
  {
    id: "GOV-193",
    name: "Sealed Chambers",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Echoes of nothing important.",
  },
  {
    id: "GOV-194",
    name: "Denial Cascade",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "A waterfall of 'no comment'.",
  },
  {
    id: "GOV-195",
    name: "Blackout Curtain",
    faction: "government",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "The stagehands run the show.",
  },
  {
    id: "GOV-196",
    name: "FOIA Glacier",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Requests go in. Winters come out.",
  },
  {
    id: "GOV-197",
    name: "Chain of Custody",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Evidence of control.",
  },
  {
    id: "GOV-198",
    name: "Overnight Curfew",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Lights out means mics off.",
  },
  {
    id: "GOV-199",
    name: "Anonymous Senior Official",
    faction: "government",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Sources say sources exist.",
  },
  {
    id: "GOV-200",
    name: "The Ceiling Above the Council",
    faction: "government",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Even the shadow has a shadow.",
  },
  {
    id: "GOV-001",
    name: "Routine Training Exercise",
    faction: "government",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "\"Nothing to see here. Please remain calm.\"",
  },
  {
    id: "GOV-002",
    name: "Redacted Press Briefing",
    faction: "government",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "The fewer words, the safer the world.",
  },
  {
    id: "GOV-003",
    name: "Continuity of Government Protocol",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Democracy is great. Backups are greater.",
  },
  {
    id: "GOV-004",
    name: "Classified Briefing Room",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "No windows, two clocks, three alarms.",
  },
  {
    id: "GOV-005",
    name: "FOIA Slow-Walk",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Your transparency request is very important to us.",
  },
  {
    id: "GOV-006",
    name: "Operation Mockingbird II",
    faction: "government",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Tonight's top story was approved at noon.",
  },
  {
    id: "GOV-007",
    name: "National Security Waiver",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "In the interest of national serenity.",
  },
  {
    id: "GOV-008",
    name: "Budget Reprogramming",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Line items are a state of mind.",
  },
  {
    id: "GOV-009",
    name: "Men in Charcoal",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "They don't need badges when they have clipboards.",
  },
  {
    id: "GOV-010",
    name: "Compartmentalization",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "The left hand files the right hand.",
  },
  {
    id: "GOV-011",
    name: "Intercept & Disrupt",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Static is the sound of safety.",
  },
  {
    id: "GOV-012",
    name: "Crisis Actor Auditions",
    faction: "government",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Please cry on lines two and three.",
  },
  {
    id: "GOV-013",
    name: "Roswell Storage Hangar",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Crates labeled 'Weather Balloon' (wink).",
  },
  {
    id: "GOV-014",
    name: "Emergency Broadcast Override",
    faction: "government",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Your regularly scheduled reality will return shortly.",
  },
  {
    id: "GOV-015",
    name: "SIGINT Sweep",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "If it beeped, we kept it.",
  },
  {
    id: "GOV-016",
    name: "Plausible Deniability",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "We can neither confirm nor deny that we denied.",
  },
  {
    id: "GOV-017",
    name: "Underground Briefing Theater",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Seats 12, alarms 13.",
  },
  {
    id: "GOV-018",
    name: "Shell Company Carousel",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Money laundering? Please, we dry-clean it.",
  },
  {
    id: "GOV-019",
    name: "Counter-Meme Task Force",
    faction: "government",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Clip art is a weapon system.",
  },
  {
    id: "GOV-020",
    name: "Honeytrap Asset",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Sign here. Smile there.",
  },
  {
    id: "GOV-021",
    name: "National Security Letter",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Gag orders pair well with coffee.",
  },
  {
    id: "GOV-022",
    name: "Ghost Budget Annex",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Zeroes are patriotic.",
  },
  {
    id: "GOV-023",
    name: "Airport Backroom",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Shoes off. Beliefs off.",
  },
  {
    id: "GOV-024",
    name: "Cutout Courier",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Trust the trench coat.",
  },
  {
    id: "GOV-025",
    name: "Cigarette Whisperer",
    faction: "government",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "The smoke alarm is for show.",
  },
  {
    id: "GOV-026",
    name: "Operation Paper Shuffle",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Filed under 'Sometime'.",
  },
  {
    id: "GOV-027",
    name: "Denver Airport Bunker",
    faction: "government",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "Art, tunnels, and a lot of keycards.",
  },
  {
    id: "GOV-028",
    name: "Black Helicopters",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "You can hear them when it's too late.",
  },
  {
    id: "GOV-029",
    name: "Declassification, Eventually",
    faction: "government",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "History will vindicate page 47.",
  },
  {
    id: "GOV-030",
    name: "Fusion Center Grid",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Interoperability is its own language.",
  },
  {
    id: "GOV-031",
    name: "Sealed Indictment",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Allegedly mandatory.",
  },
  {
    id: "GOV-032",
    name: "Telecom Compliance",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Terms of service, revised.",
  },
  {
    id: "GOV-033",
    name: "Desert Storage Yard",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Everything important is in row 51.",
  },
  {
    id: "GOV-034",
    name: "Friendly Fact-Checker",
    faction: "government",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Four Pinocchios wearing sunglasses.",
  },
  {
    id: "GOV-035",
    name: "Strategic Briefcase",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "It's full of paper and power.",
  },
  {
    id: "GOV-036",
    name: "Wilderness Listening Post",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Owls aren't what they seem. Neither are antennas.",
  },
  {
    id: "GOV-037",
    name: "Kryptek Asset",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "A handshake you don't wash off.",
  },
  {
    id: "GOV-038",
    name: "Compliance Audit",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Forms first, outrage later.",
  },
  {
    id: "GOV-039",
    name: "Press Pool Lockdown",
    faction: "government",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Coverage is a privilege.",
  },
  {
    id: "GOV-040",
    name: "Security Theater",
    faction: "government",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Now with 30% more beeping.",
  },
  {
    id: "GOV-041",
    name: "Records Sealed by Court",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Justice is blindfolded and ear-plugged.",
  },
  {
    id: "GOV-042",
    name: "Harbor Dock Warehouse",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Manifest says 'miscellaneous'.",
  },
  {
    id: "GOV-043",
    name: "Psychological Operations Cell",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "We A/B test reality.",
  },
  {
    id: "GOV-044",
    name: "Unmarked Evidence Locker",
    faction: "government",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Keyholders unknown.",
  },
  {
    id: "GOV-045",
    name: "Lizard Lobby Luncheon",
    faction: "government",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "The salad blinks first.",
  },
  {
    id: "GOV-046",
    name: "Black Budget Skunkworks",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Innovation you'll never hear about.",
  },
  {
    id: "GOV-047",
    name: "Mount Weather Complex",
    faction: "government",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "When the lights go out, these go on.",
  },
  {
    id: "GOV-048",
    name: "Witness Relocation",
    faction: "government",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "New name, same story—now quieter.",
  },
  {
    id: "GOV-049",
    name: "Council Above the Ceiling",
    faction: "government",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Minutes not taken. Decisions irreversible.",
  },
  {
    id: "GOV-050",
    name: "Executive Privilege Blanket",
    faction: "government",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "It's not a cover-up if it's a comforter.",
  },
  {
    id: "gov-1",
    name: "Propaganda Broadcast",
    faction: "government",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "They twist the truth again.",
  },
  {
    id: "gov-2",
    name: "Security Crackdown",
    faction: "government",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "A dark day for free speech.",
  },
  {
    id: "TRUTH-026",
    name: "Community Radio Tower",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Static carries secrets.",
  },
  {
    id: "TRUTH-027",
    name: "Conspiracy Bookstore",
    faction: "truth",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "Stamped 'definitely not a front'.",
  },
  {
    id: "TRUTH-028",
    name: "Lake Monster Pier",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "No refunds on splash damage.",
  },
  {
    id: "TRUTH-029",
    name: "Roadside Elvis Museum",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Wax figures hum suspiciously on Thursdays.",
  },
  {
    id: "TRUTH-030",
    name: "Paranormal Fairgrounds",
    faction: "truth",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "Tilt-a-Whirl screams back.",
  },
  {
    id: "TRUTH-031",
    name: "Tinfoil Hat Distribution Drive",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Family-pack protection.",
  },
  {
    id: "TRUTH-032",
    name: "Midnight Radio Broadcast",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "AM band, PM truths.",
  },
  {
    id: "TRUTH-033",
    name: "Tabloid Exposé",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Front page beats front line.",
  },
  {
    id: "TRUTH-034",
    name: "Ghost Hunter Raid",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "They ain't afraid of your hand size.",
  },
  {
    id: "TRUTH-035",
    name: "UFOlogist Convention",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Keynote featuring laser pointer to Orion.",
  },
  {
    id: "TRUTH-036",
    name: "Citizen Tipline Surge",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Hold, your call is very important to justice.",
  },
  {
    id: "TRUTH-037",
    name: "Phantom File Dump",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Uploaded by user 'ghost_admin'.",
  },
  {
    id: "TRUTH-038",
    name: "Witness Parade",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Everybody saw something.",
  },
  {
    id: "TRUTH-039",
    name: "Freedom of Information Blitz",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Heavily unredacted, lightly folded.",
  },
  {
    id: "TRUTH-040",
    name: "Mothman Public Warning",
    faction: "truth",
    type: "ATTACK",
    rarity: "common",
    cost: 2,
    effects: {
      ipDelta: { opponent: 1 }
    },
    flavor: "Those wings weren't for show.",
  },
  {
    id: "TRUTH-041",
    name: "Alien Foil Shield",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Cranial shine, divine design.",
  },
  {
    id: "TRUTH-042",
    name: "Community Watch",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Neighborhood eyes beat satellite spies.",
  },
  {
    id: "TRUTH-043",
    name: "Paranoia Rally",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Chant louder, doubt quieter.",
  },
  {
    id: "TRUTH-044",
    name: "Ghostly Intervention",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Invisible hands hold your hand.",
  },
  {
    id: "TRUTH-045",
    name: "Mothership Umbrella",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Broadcast jammed by cosmic drizzle.",
  },
  {
    id: "TRUTH-046",
    name: "Citizen Journalism Network",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Many eyes, fewer lies.",
  },
  {
    id: "TRUTH-047",
    name: "Tabloid Press Alliance",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Coupons clipped from reality.",
  },
  {
    id: "TRUTH-048",
    name: "Bigfoot Merchandise Store",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "Socks for enormous feet sell out instantly.",
  },
  {
    id: "TRUTH-049",
    name: "Elvis Pirate Radio",
    faction: "truth",
    type: "ZONE",
    rarity: "common",
    cost: 4,
    effects: {
      pressureDelta: 1
    },
    flavor: "All shook up… and tuned in.",
  },
  {
    id: "TRUTH-050",
    name: "Bat Boy Returns",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Running for Senate (again).",
  },
  {
    id: "TRUTH-051",
    name: "Florida Man Storms UFO Convention",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Security was no match for flip-flops and fury.",
  },
  {
    id: "TRUTH-052",
    name: "Bat Boy Runs for Mayor",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Campaign slogan: 'More Screams, Less Taxes.'",
  },
  {
    id: "TRUTH-053",
    name: "Pastor Rex Predicts Elvis Resurrection",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Sunday service includes suspicious sequins.",
  },
  {
    id: "TRUTH-054",
    name: "Tabloid Exposé: Alien Babysitter",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Best at bedtime stories, worst at curfew.",
  },
  {
    id: "TRUTH-055",
    name: "Elvis Sighted at Roswell Diner",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Thank you, fried much.",
  },
  {
    id: "TRUTH-056",
    name: "Florida Man Publishes Blog",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Powered entirely by gator energy drinks.",
  },
  {
    id: "TRUTH-057",
    name: "Haunted House Live Stream",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "Comment section full of ghosts.",
  },
  {
    id: "TRUTH-058",
    name: "Local Reporter Exposes Deep State Donuts",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Sprinkles cover more than sugar.",
  },
  {
    id: "TRUTH-059",
    name: "Bat Boy College Graduation",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Major: Paranormal Political Science.",
  },
  {
    id: "TRUTH-060",
    name: "Elvis Performs at County Fair",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Corn dogs and hound dogs.",
  },
  {
    id: "TRUTH-061",
    name: "Florida Man's UFO TikTok",
    faction: "truth",
    type: "MEDIA",
    rarity: "uncommon",
    cost: 4,
    effects: {
      truthDelta: 2
    },
    flavor: "The aliens subscribed instantly.",
  },
  {
    id: "TRUTH-062",
    name: "Pastor Rex Preaches Disclosure",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Hallelujah, the files are open.",
  },
  {
    id: "TRUTH-063",
    name: "Bat Boy Dating Show Scandal",
    faction: "truth",
    type: "MEDIA",
    rarity: "rare",
    cost: 5,
    effects: {
      truthDelta: 3
    },
    flavor: "Final rose withheld for national security.",
  },
  {
    id: "TRUTH-064",
    name: "Elvis on Mars Tabloid Scoop",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "His space suit sparkles.",
  },
  {
    id: "TRUTH-065",
    name: "Agent Smitherson's UFO Leak",
    faction: "truth",
    type: "MEDIA",
    rarity: "legendary",
    cost: 6,
    effects: {
      truthDelta: 4
    },
    flavor: "Turns out interns shouldn't have clearance.",
  },
  {
    id: "TRUTH-066",
    name: "Bat Boy Fan Club HQ",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Membership includes free capes.",
  },
  {
    id: "TRUTH-067",
    name: "Elvis Shrine Gas Station",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Fill up on miracles.",
  },
  {
    id: "TRUTH-068",
    name: "Florida Swamp Watchtower",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Mosquitoes included.",
  },
  {
    id: "TRUTH-069",
    name: "Haunted Trailer Park",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Ghosts pay rent in ectoplasm.",
  },
  {
    id: "TRUTH-070",
    name: "Pastor Rex's Tent Revival",
    faction: "truth",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "Hallelujah, the aliens are among us!",
  },
  {
    id: "TRUTH-071",
    name: "UFO Crash Carnival",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Funnel cakes taste out of this world.",
  },
  {
    id: "TRUTH-072",
    name: "Elvis Museum Basement",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Thank you, very hidden.",
  },
  {
    id: "TRUTH-073",
    name: "Bigfoot Nature Reserve",
    faction: "truth",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "Tickets include blurry binoculars.",
  },
  {
    id: "TRUTH-074",
    name: "Tabloid Printing Press",
    faction: "truth",
    type: "ZONE",
    rarity: "uncommon",
    cost: 5,
    effects: {
      pressureDelta: 2
    },
    flavor: "Hot off the paranormal presses.",
  },
  {
    id: "TRUTH-075",
    name: "Haunted Amusement Park",
    faction: "truth",
    type: "ZONE",
    rarity: "rare",
    cost: 6,
    effects: {
      pressureDelta: 3
    },
    flavor: "Roller coasters scream back.",
  }
];
