const fs = require('fs');

const ensureLimit = (list, limit) => Array.from(new Set(list)).slice(0, limit);
const ensurePeriod = (text) => {
  const trimmed = text.trim();
  if (trimmed.endsWith('.')) return trimmed;
  return `${trimmed}.`;
};
const buildSentences = (subjects, verbs, objects, codas, limit) => {
  const results = [];
  outer: for (const subject of subjects) {
    for (const verb of verbs) {
      for (const object of objects) {
        for (const coda of codas) {
          results.push(ensurePeriod(`${subject} ${verb} ${object}${coda}`));
          if (results.length >= limit) {
            break outer;
          }
        }
      }
    }
  }
  return ensureLimit(results, limit);
};

const buildSubheads = (subjects, actions, limit) => {
  const results = [];
  outer: for (const subject of subjects) {
    for (const action of actions) {
      results.push(ensurePeriod(`${subject} ${action}`));
      if (results.length >= limit) {
        break outer;
      }
    }
  }
  return ensureLimit(results, limit);
};

const verbs = {
  headline: {
    ATTACK: [
      'BURNS COVER STORY',
      'CRASHES SECURITY DRILL',
      'TORPEDOES CONTROL ROOM',
      'POPS REDACTION BUBBLE',
      'SHREDS SMOKE SCREEN',
      'RIPS OPEN OPERATIONS',
      'DERAILS BUREAU PLAN',
      'IGNITES PANIC INDEX',
      'WIRES BUGS INTO BRIEFING',
      'PUNCHES THROUGH SAFEHOUSE',
      'OUTFLANKS LOCKDOWN CREW',
      'SMASHES PANIC BUTTON',
    ],
    MEDIA: [
      'OVERRIDES PRIME TIME',
      'HIJACKS NEWS CYCLE',
      'DROWNS GOVERNMENT SPIN',
      'VIRALIZES LEAKED CLIP',
      'JAMS OFFICIAL SIGNAL',
      'LOOPS EVIDENCE ON AIR',
      'BAPTIZES AUDIENCE IN STATIC',
      'PUMPS FEEDS WITH GLITCHES',
      'TURNS RATINGS INTO SIGNAL FLARES',
      'DETONATES COMMENT SECTION',
      'SHATTERS PRESS EMBARGO',
      'SPLICED TRUTH INTO BROADCAST',
    ],
    ZONE: [
      'SEIZES STREET LEVEL',
      'OVERRUNS PRECINCT',
      'SURGES PAST ROADBLOCKS',
      'FORTIFIES STATE LINES',
      'ELEVATES GROUND GAME',
      'ENCIRCLES SKEPTIC ZONE',
      'FLOODS DISTRICT HQ',
      'ANCHORS FIELD NETWORK',
      'STACKS CLIPBOARDS SKY-HIGH',
      'WINS BACK ALLEY BATTLE',
      'UNFURLS MAP BLITZ',
      'CRACKS CURFEW GRID',
    ],
    DEFENSIVE: [
      'HARDENS SAFEHOUSE GRID',
      'LOCKS DOWN CONTACT TREE',
      'SAND BAGS THE SPIN ROOM',
      'FREEZES PANIC CHANNEL',
      'BOLTS STEEL ON RUMOR DOORS',
      'WARDS OFF ROGUE SIGNAL',
      'FORTRESSES NARRATIVE CORE',
      'HUSHES THE BRIEFING HALL',
      'PATCHES HOLES IN COVER STORIES',
      'TRIAGES PUBLIC PERIMETER',
      'STITCHES DEFENSE PLAYBOOK',
      'GARRISONS THE INFO WALL',
    ],
  },
  launch: [
    'unleashes',
    'deploys',
    'lights up',
    'scattercasts',
    'bootstraps',
    'catapults',
    'prime-times',
    'detonates',
    'rallies',
    'unspools',
    'spikes',
    'turbocharges',
  ],
  escalate: [
    'escalates',
    'amplifies',
    'magnifies',
    'inflames',
    'turbocharges',
    'snowballs',
    'powercycles',
    'overclocks',
    'dial-twists',
    'skyrockets',
    'redlines',
    'overdrives',
  ],
  scramble: [
    'scramble',
    'spin up',
    'recalibrate',
    'panic-dial',
    'reprogram',
    'triage',
    'crunch',
    'jam',
    'reroute',
    'force reboot',
    'hotfix',
    'rapid stitch',
  ],
  reassure: [
    'promise calm',
    'insist nothing is wrong',
    'schedule optics',
    'announce control',
    'hand out talking points',
    'stage a reassuring shrug',
    'tape over the warning lights',
    'print denial decals',
    'issue soothing memos',
    'declare routine turbulence',
    'offer pre-chewed statements',
    'pantomime serenity',
  ],
};

const truthSubheadSubjects = [
  'Truth syndicate scribes',
  'Witness hotline operators',
  'Basement archivists',
  'Conspiracy cartographers',
  'Signal triangulation crew',
  'Seance-certified analysts',
  'Caffeine-soaked prophets',
  'Rotating clairvoyant interns',
  'Glow-in-the-dark affidavit clerks',
  'Quantum rumor librarians',
  'Leak listeners union',
  'Field mystic correspondents',
];
const truthSubheadActions = [
  'trade annotated napkins as proof-of-life.',
  'report the evidence still hums when touched.',
  'insist the charts will not stop vibrating.',
  'mail photocopied omens to every desk.',
  'ship polaroids of spectral fingerprints.',
  'file affidavits that glow under blacklight.',
  'whisper that the facts now travel in pairs.',
  'secure lodgings for the returning prophecy.',
  'present doodled timelines that line up anyway.',
  'describe the truth as “louder than expected.”',
  'hold listening sessions with enchanted witnesses.',
  'swear the anomaly sang in four-part harmony.',
];
const governmentSubheadSubjects = [
  'Containment desk spokespersons',
  'Budget compliance ushers',
  'Crisis rehearsal moderators',
  'Spin room choreographers',
  'Official denial dispatchers',
  'Drapery-steaming protocol team',
  'Briefing room furniture whisperers',
  'Talking-point weatherproofers',
  'Policy varnish committee',
  'Statute polishing guild',
  'Narrative sanitation department',
  'Escalation paperwork wardens',
];
const governmentSubheadActions = [
  'stage a four-hour shrug for the cameras.',
  'recommend patience while smoke clears indoors.',
  'advise citizens to ignore the flashing console.',
  'insist the sirens are seasonal décor.',
  'declare the scorch marks purely symbolic.',
  'blame the sparks on imported coffee beans.',
  'promise all leaks will be recycled responsibly.',
  'explain the static as patriotic ambiance.',
  'rename the evacuation “optional stretching.”',
  'report the alarms practicing for a parade.',
  'file an intent to postpone panic until Q4.',
  'draft denial confetti just in case.',
];

const typeSubheadConfigs = {
  ATTACK: {
    subjects: [
      'Frontline spotters',
      'Counter-spin medics',
      'Firewall saboteurs',
      'Cover story pyrotechnics crew',
      'Emergency breach narrators',
      'Operative morale DJs',
      'Recon drone translators',
      'Impact assessment poets',
      'Egress choreography interns',
      'Static-proof messenger pigeons',
      'Wildfire paperwork squad',
      'Vault door locksmiths',
    ],
    actions: [
      'log scorch marks shaped like evidence.',
      'confirm security badges now smell like ozone.',
      'report alarms auditioning for a solo.',
      'warn that hush orders are fraying at the edges.',
      'paint emergency arrows toward the leaks.',
      'find footprints looping around the safe.',
      'note that drones keep high-fiving witnesses.',
      'catalog melted plastic shaped like answers.',
      'chart breach vectors on napkins mid-sprint.',
      'capture sparks in commemorative jars.',
      'time the explosions to the drumline.',
      'claim the air tastes like roasted secrecy.',
    ],
  },
  MEDIA: {
    subjects: [
      'Livestream moderators',
      'Comment section cryptanalysts',
      'Satellite wardens',
      'Control room astrologers',
      'Ratings stabilization shamans',
      'Push notification poets',
      'Caption emergency stylists',
      'Podcast foley artists',
      'Clip montage pilots',
      'Broadcast latency sculptors',
      'Signal prism custodians',
      'Monologue reheaters',
    ],
    actions: [
      'pin conspiracy emojis faster than the glitch hits.',
      'warm up static filters just to be safe.',
      'loop the evidence in seventeen dimensions.',
      'add subtitles to the whistleblower lightning.',
      'spin the headline before it combusts again.',
      'claim the waveform tastes like the truth.',
      'recalibrate cameras to catch spectral winks.',
      'order emergency pallets of sincerity filters.',
      'demand hazard pay in rare GIFs.',
      'archive the gasp track for posterity.',
      'transcribe off-mic confessions in real time.',
      'keep the “BREAKING” light stuck on neon.',
    ],
  },
  ZONE: {
    subjects: [
      'Clip-board quartermasters',
      'Door-to-door tacticians',
      'Marching order composers',
      'Polling place electricians',
      'Rally calligraphers',
      'Logistics oracles',
      'District morale coaches',
      'Sidewalk drone handlers',
      'Staging area cartographers',
      'Neighborhood mythologists',
      'Ground game choreographers',
      'Pop-up HQ baristas',
    ],
    actions: [
      'turn streetlights into megaphones overnight.',
      'report clipboards humming in unison.',
      'build morale forts out of spare signage.',
      'chalk secret runes on loading docks.',
      'map shortcut portals behind food trucks.',
      'trade foam fingers for classified intel.',
      'schedule chants that align with bus arrivals.',
      'install rumor periscopes on every porch.',
      'issue ponchos rated for data storms.',
      'flip folding tables into landing pads.',
      'calibrate megaphones to friendly frequencies.',
      'teach volunteers to waltz between raindrops.',
    ],
  },
};

const genericSubheadSubjects = [
  'Sources close to the matter',
  'Observers who refuse to blink',
  'Off-record janitorial staff',
  'Weather balloons with clearance',
  'Night shift archivists',
  'Analysts with matching stress mugs',
  'Investigators covered in glow dust',
  'Witnesses with tinfoil VIP badges',
  'Insomniac rumor biographers',
  'Forecasters with haunted spreadsheets',
  'Consultants specializing in chaos',
  'Self-appointed vibe inspectors',
];
const genericSubheadActions = [
  'call the situation “spicy with a side of déjà vu.”',
  'rate containment at two out of five fire extinguishers.',
  'report the coffee machines now dispensing pure static.',
  'debate whether the smoke is literal or narrative.',
  'phone in to say the plot just sprouted another subplot.',
  'recommend protective eyewear for the plot twists.',
  'warn that plausible deniability is on back order.',
  'insist the lighting is perfect for a confession.',
  'argue the fourth wall requested hazard pay.',
  'deliver vibe check results marked “volatile.”',
  'file noise complaints against the foreshadowing.',
  'claim even the potted plants are taking notes.',
];

const subheads = {
  truth: buildSubheads(truthSubheadSubjects, truthSubheadActions, 48),
  government: buildSubheads(governmentSubheadSubjects, governmentSubheadActions, 48),
  type: Object.fromEntries(
    Object.entries(typeSubheadConfigs).map(([key, value]) => [
      key,
      buildSubheads(value.subjects, value.actions, 48),
    ]),
  ),
  generic: buildSubheads(genericSubheadSubjects, genericSubheadActions, 48),
};

const deltaPhrases = {
  truth: {
    positive: [
      'Truth meters spike to {value} before the casing glows',
      'Polygraph ink geysers up to {value}',
      'Witness choir volume jumps by {abs} decibels',
      'Honesty seismographs thrum at {abs} on the spectrum',
      'Transparency beacons flare {value} across the skyline',
      'Veracity radars celebrate a {abs}-point upswing',
      'Fact vaults unlock {abs} new shelves of daylight',
      'Testimony oracles chant {value} in unison',
      'Signal triangulators high-five over {abs} extra truths',
      'Empathy satellites ping {value} down the chain',
      'Sworn statement reservoirs overflow by {abs}',
      'Integrity altimeters mark a {abs}-point climb',
    ],
    negative: [
      'Truth alarms cough out {abs} fewer chimes',
      'Polygraph ink smears drop to {value}',
      'Eyewitness lighthouses dim by {abs}',
      'Transparency beacons flicker {value} under minimums',
      'Fact vaults misplace {abs} shelves in the smoke',
      'Integrity gauges sag to {value}',
      'Empathy satellites lose {abs} pings in transit',
      'Witness choir volume slumps {abs} floors lower',
      'Testimony oracles whisper {value} between coughs',
      'Truth meters dip {abs} marks toward static',
      'Seers trade {abs} confirmed facts for nap time',
      'Honesty seismographs flatten by {abs}',
    ],
    neutral: [
      'Truth monitors cycle without budging a digit',
      'Polygraph reels chew on the same frame again',
      'Witnesses stare at steady lines like it is art',
      'Transparency beacons idle in patient neon',
      'Integrity altimeters hover politely at zero',
      'Fact vaults hum but refuse to open wider',
      'Empathy satellites orbit with crossed arms',
      'Truth desk plants rustle but stay at baseline',
      'Veracity sirens practice scales instead of news',
      'Signal analysts shrug at the motionless needle',
      'Testimony oracles spin their pens waiting',
      'Charts hold perfectly still out of stubbornness',
    ],
  },
  ip: {
    positive: [
      'IP siphons register {value} against the opposition ledger',
      'Bandwidth auditors applaud a {abs}-point drain',
      'Security shutters clap as {abs} IP flees the vault',
      'Counter-hackers toast {value} from enemy stores',
      'Firewall smugglers bank {abs} more stolen gigasecrets',
      'Trace routers glow {value} in reclaimed signal',
      'Leak accountants flag {abs} credits rerouted home',
      'Backdoor scribes underline {value} on the raid report',
      'Packet divers haul {abs} fresh crates of intel',
      'Cipher breakers cheer a {abs}-unit siphon',
      'Decryption drones stream {value} to friendly shelves',
      'Silent alarms wink at the {abs} gap left behind',
    ],
    negative: [
      'IP dams crack and spill {abs} into enemy basements',
      'Signal custodians watch {value} drain away',
      'Backdoor scribes bite knuckles over {abs} lost intel',
      'Leak accountants stamp {value} on the deficit column',
      'Firewall smugglers discover empty crates where {abs} lived',
      'Cipher breakers groan as {abs} packets vanish',
      'Trace routers flash warning red at {value}',
      'Bandwidth auditors mutter about {abs} evaporated gigs',
      'Silent alarms wince while {abs} secret files escape',
      'Decryption drones chase a {abs}-unit leak into shadows',
      'Security shutters squeal as {abs} slips through',
      'Packet divers report {value} missing from the nets',
    ],
    neutral: [
      'IP ledgers balance on a stubborn zero',
      'Firewall smugglers flip a coin and wait',
      'Trace routers hover at their default hum',
      'Leak accountants highlight the empty column again',
      'Cipher breakers set the kettle on for lack of news',
      'Signal custodians polish knobs hoping for motion',
      'Bandwidth auditors synchronize watches with nothing to tally',
      'Packet divers float in place awaiting coordinates',
      'Silent alarms nap with one light open',
      'Security shutters creak but stay put',
      'Backdoor scribes doodle while the graphs flatline',
      'Decryption drones hover above a static sea',
    ],
  },
  pressure: {
    positive: [
      'Pressure gauges pound up to {value}',
      'Stress barometers crackle {abs} ticks higher',
      'Tension sirens redline at {value}',
      'Overwatch medics log {abs} new stress fractures',
      'Containment coaches shout about {value} units incoming',
      'Anxiety drones whirl {abs} laps faster',
      'Support lines buzz with {abs} extra calls',
      'Compliance pumps grind under {value}',
      'Morale thermostats spike by {abs}',
      'Hydraulic rumor presses squeal at {value}',
      'Thermal charts bubble {abs} columns hotter',
      'Logbooks mark {abs} more panic signatures',
    ],
    negative: [
      'Pressure gauges sigh down to {value}',
      'Stress barometers shed {abs} frantic ticks',
      'Tension sirens downgrade to polite beeps',
      'Containment coaches hand out {abs} calm badges',
      'Anxiety drones glide {abs} laps slower',
      'Support lines report {abs} fewer trembling callers',
      'Morale thermostats drift toward breezy settings',
      'Logbooks erase {abs} red exclamation points',
      'Hydraulic rumor presses exhale at {value}',
      'Thermal charts simmer {abs} gradients cooler',
      'Compliance pumps coast on {abs} lighter loads',
      'Pressure vaults vent {abs} units into the night air',
    ],
    neutral: [
      'Pressure gauges refuse to blink',
      'Stress barometers hold a poker face',
      'Tension sirens hum scales to pass the time',
      'Containment coaches stretch and wait',
      'Anxiety drones idle in slow orbits',
      'Support lines restock tea for a quiet minute',
      'Logbooks balance open pages on nothing in particular',
      'Compliance pumps maintain their indoor voices',
      'Morale thermostats hover at lukewarm',
      'Hydraulic rumor presses tap their pens',
      'Thermal charts loop the same slideshow again',
      'Pressure vaults lounge with the door ajar',
    ],
  },
  summary: [
    'Analysts report phantom metrics ricocheting through the dashboards.',
    'Data clerks shrug in perfect formation as the needles hold still.',
    'Dashboards blink politely, waiting for the next measurable omen.',
    'Clipboard astrologers circle zero and call it suspense.',
    'Metrics interns log today as “narratively inconclusive.”',
    'Monitoring spirits whisper that the numbers crave more drama.',
    'Systems rest on their laurels, daring the plot to escalate.',
    'Data scribes document the eerie calm before the next spike.',
    'Telemetry custodians fold their hands and listen for a distant boom.',
    'Analytics oracles mark the graphs “ominously quiet.”',
  ],
};

const stateTargetSetups = [
  'Dispatch from {state}',
  '{state} field bureau',
  'Local midnight desk in {state}',
  'County rumor hotline in {state}',
  '{state} surveillance balloons',
  'District seers posted in {state}',
  'Neighborhood beacon keepers in {state}',
  '{state} campus radio conspiracists',
  'Courier pigeons arriving from {state}',
  'Arcane poll watchers across {state}',
  'Chalkboard scribes stationed in {state}',
  'Stargazers leaning over {state}',
];
const stateTargetActions = [
  'report sirens teaching the alleys new lyrics.',
  'transmit coordinates for a fresh rumor storm.',
  'fax in sketches of agents scaling fire escapes.',
  'note volunteers handing out whisperproof ponchos.',
  'tune receivers to the rumble of gathering crowds.',
  'claim every porch light just blinked twice in Morse.',
  'hear chanting echoing off the courthouse glass.',
  'warn that static fog is spilling from the rotunda.',
  'showcase traffic cones vibrating in anticipation.',
  'count clipboards orbiting like curious satellites.',
  'register midnight crowds rehearsing testimony.',
  'invite reinforcements before the story hardens.',
];

const stateCaptureSingleSetups = [
  'Cartographers redraw the map as {state}',
  'Celebratory seismographs tremble once {state}',
  'Courier drones loop victory laps above {state}',
  'District rumor mills applaud because {state}',
  'Ground teams radio that {state}',
  'Signal bunkers declare {state}',
  'Field captains toast as {state}',
  'Campaign dramaturges scribble exclamation marks when {state}',
  'Narrative fire marshal confirms {state}',
  'Arcane poll watchers engrave that {state}',
  'Strategic chalk artists update the wall: {state}',
  'Overtime clerks high-five, shouting that {state}',
];
const stateCaptureSingleActions = [
  'flips before the coffee cools.',
  'slides into our column like it always belonged.',
  'broadcasts a brand-new chant from the capitol steps.',
  'surrenders its passwords with theatrical flair.',
  'raises the banner and retires the caution tape.',
  'declares every diner a safehouse effective immediately.',
  'turns main street into a celebration runway.',
  'orders commemorative glowsticks for every precinct.',
  'sends thank-you notes to the rumor couriers.',
  'invites the press to witness the midnight confetti.',
  'updates road signs to include “Victory Blvd.”',
  'shuts off the alarm and opens the truth skylights.',
];

const stateCaptureMultipleSetups = [
  'Cartographers scramble as {list}',
  'Logistics wizards juggle clipboards because {list}',
  'Ground control shouts in chorus when {list}',
  'Campaign narrators barely keep up while {list}',
  'Signal bunkers broadcast fireworks after {list}',
  'Parade marshals re-route the route since {list}',
  'Strategists high-five wildly as {list}',
  'Beacon keepers sketch constellations for {list}',
  'Field seers rewrite their prophecy once {list}',
  'Courier pigeons deliver glittery notices that {list}',
  'District rumor drums pound louder when {list}',
  'Clipboard brigades erupt into song because {list}',
];
const stateCaptureMultipleActions = [
  'all flip in unison.',
  'decide the suspense has lasted long enough.',
  'hand over their keys with synchronized grins.',
  'light up the skyline with improvised pyrotechnics.',
  'take a group selfie beside the retired barricades.',
  'rename the freeway “Victory Express” on the spot.',
  'mail the opposition a sympathy fruit basket.',
  'sign the rumor ledger in glitter ink.',
  'send parade permits signed in neon.',
  'ping the satellite array with triumphant static.',
  'host a multistate celebratory conference call.',
  'schedule a traveling victory marching band.',
];

const cleanTemplateList = (list) => list.map((entry) => entry.replace(/  +/g, ' '));

const statePhrases = {
  target: cleanTemplateList(
    buildSentences(stateTargetSetups, [''], stateTargetActions, [''], 144).map((line) => line.replace('  ', ' '))
  ),
  capturedSingle: cleanTemplateList(
    buildSentences(stateCaptureSingleSetups, [''], stateCaptureSingleActions, [''], 144).map((line) => line.replace('  ', ' '))
  ),
  capturedMultiple: cleanTemplateList(
    buildSentences(stateCaptureMultipleSetups, [''], stateCaptureMultipleActions, [''], 144).map((line) => line.replace('  ', ' '))
  ),
  fallback: [
    'Local scouts sketch uncertain sigils onto the precinct walls.',
    'Statehouse windows fog with anticipation and static.',
    'Pundits debate whether the map is already morphing itself.',
    'Onlookers prep celebratory playlists just in case.',
    'Rumor couriers stretch their legs for the final sprint.',
    'District cartographers pre-shuffle their colored pencils.',
    'Fog machines idle politely near the welcome banner.',
    'Volunteer DJs queue up the triumphant chorus.',
    'Security owls swivel toward the next big flip.',
    'Local archivists dust off the victory ledger.',
  ],
};

const connectors = {
  leadIns: [
    'Analysts log',
    'Telemetry scribes report',
    'Dashboard oracles mutter',
    'Crisis statisticians scribble',
    'Control room seers confirm',
    'Metrics custodians whisper',
    'Signal interpreters chant',
    'Data couriers broadcast',
    'Quant shamans interpret',
    'Narrative auditors highlight',
    'Graph wranglers warn',
    'Scorekeepers tally',
    'Pulse readers describe',
    'Operational astrologers chart',
    'Monitor druids intone',
  ],
  joiners: [
    'while',
    'as',
    'and',
    'before',
    'during',
    'even as',
    'meanwhile',
    'just as',
    'because',
    'right when',
    'until',
    'after',
    'beside the moment',
    'in tandem as',
    'once',
  ],
  codas: [
    'before the dashboards sprout sparks.',
    'until the graphs start belting show tunes.',
    'while the control room lights cycle through panic mode.',
    'before the metrics burst into celebratory confetti.',
    'and the analysts demand hazard pay in foil.',
    'just as the monitors request a five-minute breather.',
    'until the servers plead for a cool-down.',
    'before the whiteboards melt into abstract art.',
    'and the audit spirits fist-bump in the vents.',
    'while the charts flash paparazzi lightning.',
    'right as the data center orders celebratory pizza.',
    'until the briefing room applauds with both hands.',
    'while the forecast printers spit out glitter.',
    'before the crisis clock resets in disbelief.',
    'and the telemetry owls hoot the victory chorus.',
  ],
};

const truthBanksConfig = {
  ATTACK: {
    subjects: [
      'Basement seers',
      'Signal scrapers',
      'Truthfront raiders',
      'Data-flood commandos',
      'Covert archivists',
      'Static saboteurs',
      'Vigil prophets',
      'Night shift infiltrators',
      'Cipher poets',
      'Ghost frequency riders',
    ],
    verbs: [
      'lance',
      'phase through',
      'melt',
      'rewire',
      'short-circuit',
      'detonate',
      'perforate',
      'rewind',
      'smuggle past',
      'overwhelm',
    ],
    objects: [
      'bureaucratic smoke screens',
      'lockstep cover stories',
      'panic room buzzers',
      'confiscated dossiers',
      'denial echo chambers',
      'paper-thin alibis',
      'sterile press kits',
      'nightwatch defenses',
      'security holograms',
      'classified rumor vaults',
      'carbon-copied excuses',
      'silent alarm choreography',
    ],
    codas: [
      'before sunrise finds them grinning',
      'while the alarms argue over volume',
      'as the sprinkler system applauds',
      'during synchronized espresso shots',
      'with searchlights doing double takes',
      'as the elevator refuses to move',
      'while rival agents write furious notes',
      'before the janitors notice the glow',
      'while the sirens remix themselves',
      'during a blackout shaped like victory',
      'as the rumor mill spins into overdrive',
      'while security badges quietly melt',
    ],
  },
  MEDIA: {
    subjects: [
      'Signal poets',
      'Frequency smugglers',
      'Neon pundit guild',
      'Conspiracy remixers',
      'Broadcast mystics',
      'Static librarians',
      'Guerilla documentarians',
      'Teleprompter saboteurs',
      'Viral archivists',
      'Caption conjurers',
    ],
    verbs: [
      'loop',
      'hypercast',
      'splice',
      'detour',
      'glitch',
      'beam',
      'drench',
      'remix',
      'telegraph',
      'overclock',
    ],
    objects: [
      'the prime-time firewall',
      'censor-approved headlines',
      'emergency crawl scripts',
      'algorithmic talking points',
      'sponsored reality bubbles',
      'focus group lullabies',
      'televised smokescreens',
      'mid-scroll amnesia',
      'off-air confessionals',
      'studio denial fields',
      'ratings containment grids',
      'comment section jammers',
    ],
    codas: [
      'until the broadcast booth glows',
      'while moderators reboot on loop',
      'as the control board speaks in tongues',
      'before producers can find the mute switch',
      'while captions rewrite themselves',
      'during a nationwide static bloom',
      'as pundits frantically reapply makeup',
      'while sponsors reconsider their slogans',
      'before the streaming delay catches up',
      'as interns chase runaway cables',
      'while viewers spam the emergency emote',
      'during a ratings spike shaped like a comet',
    ],
  },
  ZONE: {
    subjects: [
      'Canvas cartographers',
      'Doorstep storytellers',
      'Volunteer phalanx',
      'Ground game astronomers',
      'Clipboard nomads',
      'Flyer constellation crews',
      'Bus stop heralds',
      'Parking lot prophets',
      'Sidewalk signal corps',
      'Neighborhood pulse keepers',
    ],
    verbs: [
      'flood',
      'rewire',
      'ignite',
      'enchant',
      'seed',
      'braid',
      'magnetize',
      'supercharge',
      'illuminate',
      'rethread',
    ],
    objects: [
      'cul-de-sac rumor mills',
      'community center backrooms',
      'folding chair strongholds',
      'diner jukebox alliances',
      'field office auroras',
      'porch light dispatches',
      'mall atrium whispers',
      'county fair conduits',
      'town square storytellers',
      'bus depot war rooms',
      'midnight canvass trails',
      'precinct snack bunkers',
    ],
    codas: [
      'until curfew gives up',
      'while porch lights nod along',
      'as streetcorners bloom with signal',
      'before the map can catch its breath',
      'while the marching band hits remix mode',
      'during a drizzle of glittering flyers',
      'as local mascots swap sides',
      'while residents wave from rooftops',
      'during synchronized scooter maneuvers',
      'as rumor lanterns float skyward',
      'before the road cones finish applauding',
      'while the festival lights stay overtime',
    ],
  },
  NEUTRAL: {
    subjects: [
      'Chronicle ghosts',
      'Archive spelunkers',
      'Coffee cart prophets',
      'Lobby eavesdroppers',
      'Atrium stargazers',
      'Mailroom truthers',
      'Hallway detectives',
      'Copy room mystics',
      'Skybridge narrators',
      'Breakroom augurs',
    ],
    verbs: [
      'document',
      'decode',
      'sketch',
      'catalog',
      'bookmark',
      'choreograph',
      'foreshadow',
      'annotate',
      'index',
      'stage-manage',
    ],
    objects: [
      'glitch-kissed memos',
      'rumors with post-it wings',
      'elevated coincidences',
      'foyer whispers',
      'staticky elevator rides',
      'dimly lit copy jobs',
      'meeting room echoes',
      'budget margin omens',
      'press pool rumors',
      'after-hours schematics',
      'sightings scribbled on napkins',
      'phantom phone trees',
    ],
    codas: [
      'before the janitor flips the lights',
      'while the vending machine hums conspiracies',
      'as the badge readers blink uncertainly',
      'during a lull in the panic soundtrack',
      'with the breakroom plant nodding along',
      'while the elevators take the scenic route',
      'before dawn sneaks up on the lobby',
      'as the night crew swaps prophecies',
      'while the copier warms its second sight',
      'during intermission for plausible deniability',
      'as the hallway cameras pretend not to notice',
      'while the rumor cloud thunders softly',
    ],
  },
};

const governmentBanksConfig = {
  ATTACK: {
    subjects: [
      'Containment tacticians',
      'Panic control marshals',
      'Emergency optics staff',
      'Briefing bunker supervisors',
      'Security doctrine clerks',
      'Redaction locksmiths',
      'Official calm brigade',
      'Incident paperwork cavalry',
      'Backchannel weather team',
      'Damage control dramaturges',
    ],
    verbs: [
      'sandbag',
      'reinforce',
      'triage',
      'buffer',
      'redirect',
      'calibrate',
      'dampen',
      'cordon',
      'quarantine',
      'brace',
    ],
    objects: [
      'the breach narrative',
      'rumor aftershocks',
      'alarm sirens',
      'scorch-mark speculation',
      'panic reports',
      'smoke plume metaphors',
      'leak-stained briefing notes',
      'emergency press kits',
      'unruly camera crews',
      'shredded cover sheets',
      'foyer rumor fog',
      'rogue testimony loops',
    ],
    codas: [
      'before senior staff returns from lunch',
      'while the microphones cycle feedback',
      'as interns roll out the denial podium',
      'during a surprise inspection from oversight',
      'with the sprinkler system politely offline',
      'as legal counsel highlights calming adjectives',
      'while the security drones request updates',
      'before the next rumor truck parks outside',
      'while the siren playlist tries smooth jazz',
      'as the lobby clock skips backwards',
      'during an unscheduled calm rehearsal',
      'while the fire doors finish their sigh',
    ],
  },
  MEDIA: {
    subjects: [
      'Broadcast compliance crews',
      'Optics harmonizers',
      'Studio serenity managers',
      'Teleprompter legalists',
      'Ratings stabilizers',
      'Satellite custodians',
      'Press pool wranglers',
      'Syndication referees',
      'Narrative captioners',
      'Sponsor relations envoys',
    ],
    verbs: [
      'rebalance',
      'slow-bake',
      'buffer',
      'retime',
      'soft-focus',
      'coolant-spray',
      'desaturate',
      'deglitch',
      'muffle',
      'fine-tune',
    ],
    objects: [
      'the emergency crawl',
      'comment avalanche',
      'viral leak loops',
      'overexcited pundit table',
      'sizzling conspiracy memes',
      'rogue camera angles',
      'studio static fields',
      'late-night speculation',
      'ratings wildfire',
      'pirated feed fragments',
      'open-mic admissions',
      'caption typos',
    ],
    codas: [
      'until the telecast looks responsibly dull',
      'while the sponsor rep breathes into a paper bag',
      'as producers label every light “do not touch”',
      'before the regulator pings for an update',
      'while the studio cat naps on the switchboard',
      'during the mandated calm montage',
      'as PR drafts the next apology scaffold',
      'while focus groups practice nodding',
      'before the satire accounts notice',
      'as the control booth power cycles politely',
      'while the hotline screens the next caller',
      'during a carefully curated silence break',
    ],
  },
  ZONE: {
    subjects: [
      'Logistics quartermasters',
      'Permit compliance captains',
      'Message discipline patrols',
      'Curfew alignment staff',
      'Field optics liaisons',
      'Perimeter stewards',
      'Volunteer credentialers',
      'Staging tent supervisors',
      'Municipal negotiation teams',
      'Ground operation auditors',
    ],
    verbs: [
      'coordinate',
      'standardize',
      'de-escalate',
      'route',
      'stage',
      'stabilize',
      'temper',
      'meter',
      'tidy',
      'catalog',
    ],
    objects: [
      'crowd surge reports',
      'clipboards migrating in herds',
      'megaphone duels',
      'canteen rumors',
      'banner placement debates',
      'side street rallies',
      'folding chair rebellions',
      'parking lot broadcasts',
      'district rumor eddies',
      'ward-level shockwaves',
      'march cadence arguments',
      'pop-up barricade art',
    ],
    codas: [
      'before the mayor checks the livestream',
      'while the curfew drones negotiate overtime',
      'as local news helicopters hover politely',
      'during a community-approved calm-down playlist',
      'with the sanitation crew asking for clearer signage',
      'as the event permit printer smokes softly',
      'while volunteers rehearse the approved chant',
      'before the streetlights finish dimming',
      'as the parade route draws a breath',
      'during crosswalk synchronization drills',
      'while vendors serve decaf diplomacy lattes',
      'as the rumor desk tallies borrowed bullhorns',
    ],
  },
  NEUTRAL: {
    subjects: [
      'Policy archivists',
      'Budget whisperers',
      'Protocol librarians',
      'Atrium liaison officers',
      'Security plant caretakers',
      'Message calibration aides',
      'Compliance scribes',
      'Breakroom supervisors',
      'Internal comms narrators',
      'Lobby acoustics consultants',
    ],
    verbs: [
      'catalog',
      'footnote',
      'index',
      'document',
      'cross-reference',
      'clarify',
      'proofread',
      'annotate',
      'standardize',
      'update',
    ],
    objects: [
      'late-night memos',
      'rumor mitigation forms',
      'security badge requests',
      'conference room echoes',
      'unfiled observation decks',
      'elevator etiquette guides',
      'panic rehearsal scripts',
      'committee snack inventories',
      'talking point drafts',
      'lobby acoustic schematics',
      'spillover agenda items',
      'pending calm bulletins',
    ],
    codas: [
      'while the office plants soak up static',
      'before sunrise finds the conference table',
      'as the escalators yawn politely',
      'during the designated reflection pause',
      'while the vending machine dispenses only decaf',
      'before the badge readers reboot',
      'as the custodial staff swaps rumor notes',
      'while the intercom hums a lullaby',
      'during scheduled breathing exercises',
      'while the compliance owl watches quietly',
      'as the clock contemplates a redo',
      'before the morning briefing fogs the glass',
    ],
  },
};

const buildFactionBank = (config, limit) =>
  Object.fromEntries(
    Object.entries(config).map(([key, value]) => [
      key,
      buildSentences(value.subjects, value.verbs, value.objects, value.codas, limit),
    ])
  );

const bodyTruth = buildFactionBank(truthBanksConfig, 160);
const bodyGov = buildFactionBank(governmentBanksConfig, 160);

const tagInserts = {
  '#CryptidWatch': [
    'Cryptid spotters cross-reference footprints with budget leaks.',
    'Night vision reveals antlered silhouettes signing autographs.',
    'Experts debate if the roar was a yeti or a loose HVAC vent.',
    'Volunteer folklorists diagram claw marks onto city permits.',
    'Dashboard naturalists request hazard pay in silver bullets.',
    'Museum interns polish display cases for incoming evidence.',
  ],
  '#PumpkinSpicePanic': [
    'Seasonal lattes now require paranormal waivers.',
    'Jack-o’-lantern lighting crews demand hazard pay in candy corn.',
    'Capes and cloaks sold out before sunrise—again.',
    'Cider fountains run dry as baristas fortify the perimeter.',
    'Cinnamon dust triggers the evacuation sirens thrice.',
    'Local gourds file for protective custody.',
  ],
  '#ContactProtocol': [
    'Radar techs swear the blip winked at them in Morse.',
    'Beam team requisitions extra sunglasses for post-contact glare.',
    'Phone banks reroute calls from “space unknown” to voicemail.',
    'Diplomats rehearse greetings in five speculative dialects.',
    'Launchpads clear for the ceremonial welcome mat.',
    'Signal translators queue the universal hold music.',
  ],
  '#MonsterMashup': [
    'Emergency DJ asked to remix the wails into a dance beat.',
    'Fog machine union issues cease-and-desist on dramatic entrances.',
    'Silver bullet budget hearings moved to the moonlight shift.',
    'Costume designers patent claw-resistant sequins.',
    'Spectator bleachers sprout garlic garlands overnight.',
    'Choreographers map out a safe conga line around the cryptids.',
  ],
  '#RedactedOps': [
    'Briefing packets arrive pre-shredded for convenience.',
    'Laser pointers identify six separate scapegoats.',
    'Elevator music replaced with ominous thudding bass.',
    'Security pens leak censor ink on sight.',
    'Clipboard shadows fall exactly where the secrets hide.',
    'Badge scanners mutter “classified” and open anyway.',
  ],
  '#FieldWorkFrenzy': [
    'Clipboards multiply faster than the copy room can count.',
    'Volunteers report sneakers squeaking in triumphant harmony.',
    'Traffic cones promoted to honorary colonels.',
    'Snack tables earn medals for endurance.',
    'Logistics radios schedule a hydration encore.',
    'Door-knock playlists hit their seventeenth remix.',
  ],
  '#LeakSeason': [
    'Umbrellas deploy indoors as truth drips from fluorescent fixtures.',
    'Whistleblowers swap ponchos for VIP seats by the leak fountain.',
    'Collectors bid on limited-edition drip buckets stamped CLASSIFIED.',
    'Maintenance crews install gutters under the rumor cloud.',
    'Cleanup teams break out the industrial-strength towels.',
    'Forecast maps predict 100% chance of confession.',
  ],
  '#NarrativeContainment': [
    'Containment vans idle while agents tape stray rumors to clipboards.',
    'Firewall marshals shovel canned talking points into the breach.',
    'Spokespeople herd gossip into color-coded binders by flashlight.',
    'Legal advisors weigh the cost of floodwalls made of NDAs.',
    'Calming playlists loop across the emergency PA system.',
    'Containment drones spray foam over runaway metaphors.',
  ],
  '#TruthSignal': [
    'Ham radio clusters triangulate the freshest truth pings.',
    'Basement antennas hum in jubilation at the resonance spike.',
    'Fact scouts synchronize watches to the latest honesty flare.',
    'Beacon keepers hoist flags for every confirmed ping.',
    'Signal historians log each chord change in the static hymn.',
    'Neighborhood rooftops flash foil-coded confirmations.',
  ],
  '#ContainmentBureau': [
    'Briefers pin medals on the steadiest bureaucratic poker faces.',
    'Clipboard brigades salute the official silence without blinking.',
    'Budget czars remind staff the paperwork already won this round.',
    'Containment mascots practice their dignified wave.',
    'Policy metronomes keep everyone on the same beat.',
    'Compliance drones knit calm scarves for the interns.',
  ],
  '#DirectAction': [
    'Boot prints smear across the incident command whiteboard.',
    'Emergency sirens harmonize with rapid-fire press releases.',
    'Operatives high-five over evidence crates still sparking.',
    'Reinforcement vans arrive with celebratory klaxons.',
    'Field medics autograph the scorch marks.',
    'Tactical drones spell victory in laser cursive.',
  ],
  '#BroadcastSpin': [
    'Studio gels melt under the rebuttal reel’s intensity.',
    'Teleprompters flash hazard warnings between every bullet point.',
    'Makeup crews contour panic into heroic resolve on air.',
    'Producers stagger commercial breaks to catch their breath.',
    'Anchor desks vibrate with contained outrage.',
    'Caption bots add exclamation marks without permission.',
  ],
  '#GroundSurge': [
    'Field kitchens ladle morale stew into collapsible mugs.',
    'Clipboard caravans annex every folding chair in sight.',
    'Marching orders echo down cul-de-sacs until porch lights salute.',
    'Volunteer DJs loop the rally anthem for the third encore.',
    'Neighborhood mascots don borrowed campaign hats.',
    'Transit lines extend for the celebratory late-night run.',
  ],
  '#ParanoidPress': [
    'Interns refresh the rumor CMS twice a heartbeat.',
    'Newsroom houseplants lean closer to catch the whisper net.',
    'Editors stockpile midnight toner for the next revelation.',
    'Fact-checkers draft apologies to their future selves.',
    'Night desk reporters trade caffeine for conspiracy.',
    'Headline bots request a raise for danger pay.',
  ],
  default: [
    'Atmospheric sensors detect elevated levels of dramatic irony.',
    'Insiders suggest investing in metaphysical seatbelts.',
    'Plausible deniability filed for a stress leave.',
    'Forecast calls for scattered revelations and thunderous applause.',
    'Even the background music demanded a rewrite.',
    'Narrative humidity climbs to record highs.',
  ],
};

const playerLabels = {
  human: 'Operative network',
  ai: 'Opposition machine',
};

const formatValue = (value, indent = 0) => {
  const spacing = '  '.repeat(indent);
  if (Array.isArray(value)) {
    const inner = value
      .map((item, index) => {
        const formatted = formatValue(item, indent + 1);
        const trailing = index === value.length - 1 ? '' : ',';
        return `${spacing}  ${formatted}${trailing}`;
      })
      .join('\n');
    return `[` + (inner ? `\n${inner}\n${spacing}` : '') + `]`;
  }
  if (value && typeof value === 'object') {
    const entries = Object.entries(value)
      .map(([key, val], index, arr) => {
        const formatted = formatValue(val, indent + 1);
        const trailing = index === arr.length - 1 ? '' : ',';
        return `${spacing}  ${JSON.stringify(key)}: ${formatted}${trailing}`;
      })
      .join('\n');
    return `{` + (entries ? `\n${entries}\n${spacing}` : '') + `}`;
  }
  return JSON.stringify(value);
};

const sections = [
  "import type { Card } from '@/types';",
  '',
  `export const verbs = ${formatValue(verbs)} satisfies {\n  headline: Record<Card['type'], string[]>;\n  launch: string[];\n  escalate: string[];\n  scramble: string[];\n  reassure: string[];\n};`,
  '',
  `export const subheads = ${formatValue(subheads)} satisfies {\n  truth: string[];\n  government: string[];\n  type: Record<'ATTACK' | 'MEDIA' | 'ZONE', string[]>;\n  generic: string[];\n};`,
  '',
  `export const deltaPhrases = ${formatValue(deltaPhrases)} satisfies {\n  truth: Record<'positive' | 'negative' | 'neutral', string[]>;\n  ip: Record<'positive' | 'negative' | 'neutral', string[]>;\n  pressure: Record<'positive' | 'negative' | 'neutral', string[]>;\n  summary: string[];\n};`,
  '',
  `export const statePhrases = ${formatValue(statePhrases)} satisfies {\n  target: string[];\n  capturedSingle: string[];\n  capturedMultiple: string[];\n  fallback: string[];\n};`,
  '',
  `export const connectors = ${formatValue(connectors)} satisfies {\n  leadIns: string[];\n  joiners: string[];\n  codas: string[];\n};`,
  '',
  `export const bodyTruth = ${formatValue(bodyTruth)} satisfies Record<'ATTACK' | 'MEDIA' | 'ZONE' | 'NEUTRAL', string[]>;`,
  '',
  `export const bodyGov = ${formatValue(bodyGov)} satisfies Record<'ATTACK' | 'MEDIA' | 'ZONE' | 'NEUTRAL', string[]>;`,
  '',
  `export const tagInserts = ${formatValue(tagInserts)} satisfies Record<string, string[]>;`,
  '',
  `export const playerLabels = ${formatValue(playerLabels)} satisfies Record<'human' | 'ai', string>;`,
  '',
];

fs.writeFileSync('src/engine/newspaper/StoryBanks.ts', sections.join('\n') + '\n');
