import { readdir } from 'node:fs/promises';
import { join, parse } from 'node:path';
import { fileURLToPath } from 'node:url';
import { writeFile } from 'node:fs/promises';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const root = join(__dirname, '..');
const cardArtDir = join(root, 'public', 'card-art');
const manifestPath = join(root, 'src', 'data', 'cardArtManifest.ts');

async function buildManifest() {
  const entries = await readdir(cardArtDir);
  const names = entries
    .filter(name => !name.startsWith('.'))
    .map(name => parse(name).name)
    .filter(Boolean)
    .sort((a, b) => a.localeCompare(b));
  const unique = Array.from(new Set(names));
  const contents = `// This file is auto-generated by tools/update-card-art-manifest.ts\n` +
    `export const AVAILABLE_CARD_ART = new Set<string>(` +
    `${JSON.stringify(unique, null, 2)});\n`;
  await writeFile(manifestPath, contents, 'utf8');
}

buildManifest().catch(error => {
  console.error('Failed to update card art manifest', error);
  process.exit(1);
});
